name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SECRET_SNYK }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: make setup
      - run: make test
      - run: make lint
