
name: Setup and check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: make setup
      - run: make lint
      - run: make test
      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.Secret_SNYK }}
